// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-MkHs95S2kKK2aJoNWx3vwVQKT53hBNI',
    appId: '1:916104635578:web:151fde6c0455f978a84e83',
    messagingSenderId: '916104635578',
    projectId: 'unipulse-63ea1',
    authDomain: 'unipulse-63ea1.firebaseapp.com',
    storageBucket: 'unipulse-63ea1.firebasestorage.app',
    measurementId: 'G-W7R45HNF78',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXdVG1a-DzSjgTGWPkyYSDfTJQzceJYcs',
    appId: '1:916104635578:android:e8e845709d58258ca84e83',
    messagingSenderId: '916104635578',
    projectId: 'unipulse-63ea1',
    storageBucket: 'unipulse-63ea1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnsgsODWBnpzF1rrN1UYu_pf2LwoRYHjs',
    appId: '1:916104635578:ios:aeced55c8900af39a84e83',
    messagingSenderId: '916104635578',
    projectId: 'unipulse-63ea1',
    storageBucket: 'unipulse-63ea1.firebasestorage.app',
    iosBundleId: 'com.example.campusSignal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnsgsODWBnpzF1rrN1UYu_pf2LwoRYHjs',
    appId: '1:916104635578:ios:aeced55c8900af39a84e83',
    messagingSenderId: '916104635578',
    projectId: 'unipulse-63ea1',
    storageBucket: 'unipulse-63ea1.firebasestorage.app',
    iosBundleId: 'com.example.campusSignal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-MkHs95S2kKK2aJoNWx3vwVQKT53hBNI',
    appId: '1:916104635578:web:23e562b260ec6b0ca84e83',
    messagingSenderId: '916104635578',
    projectId: 'unipulse-63ea1',
    authDomain: 'unipulse-63ea1.firebaseapp.com',
    storageBucket: 'unipulse-63ea1.firebasestorage.app',
    measurementId: 'G-DSSPFV3PXV',
  );
}
